Repository PinkDumbbell/CocoBob-FE, pull requests merged in 2022-11, with the labels that each got.

#92 [CB] 산책 기록
  src/components/Confirm/ConfirmModal.style.ts
  src/components/Confirm/ConfirmModal.tsx
  src/components/Confirm/ConfirmPortal.tsx
  src/pages/Daily/Note/NotePage.tsx
  src/pages/Daily/Note/NoteWritePage.tsx
  src/pages/Daily/Walk/WalkHistoryPage.tsx
  src/pages/Daily/Walk/WalkRecordPage.tsx
  src/pages/Daily/Walk/[id].tsx
  src/pages/Daily/Walk/components/WalkHistoryList.tsx
  src/pages/Daily/Walk/components/WalkRecordDetail.tsx
  src/pages/Daily/Walk/hooks/useLocationInApp.tsx
  src/pages/Mypage/Main.tsx
  src/pages/Mypage/pets/[id]/edit.tsx
  src/pages/Mypage/pets/[id]/index.tsx
  src/store/api/dailyApi.ts
  src/utils/hooks/useConfirm.tsx
  src/utils/hooks/useLogout.tsx
  src/utils/hooks/useWithdrawal.tsx
Labels: 💻FE, ⛏Feat, 😎 Fix

#94 [CB-498] 지도 산책 저장 API 연결
  src/pages/Daily/Walk/WalkRecordPage.tsx
  src/pages/Daily/Walk/components/SaveWalkRecordModal.tsx
  src/store/api/dailyApi.ts
  src/utils/hooks/useCounter.tsx
  src/utils/libs/date.ts
Labels: 💻FE, ⛏Feat

#95 [CB-505] 산책 저장 에러 수정
  src/pages/Daily/Walk/WalkRecordPage.tsx
  src/pages/Daily/Walk/components/SaveWalkRecordModal.tsx
  src/utils/libs/date.ts
Labels: 💻FE, 😎 Fix

#98 상품 검색페이지 수정
  package-lock.json
  src/Animation/DotLoader/index.tsx
  src/Animation/Spinner/index.tsx
  src/components/layout/Header.tsx
  src/pages/Products/ProductDetail.tsx
  src/pages/Products/components/ProductDetail/RecommendInfoDetail/RecomendInfoDetail.tsx
  src/pages/Products/components/ProductDetail/index.style.ts
  src/pages/Products/components/Search/header.tsx
  src/pages/Products/components/Search/index.style.ts
  src/pages/Products/components/Search/index.tsx
  src/pages/Products/components/Search/modal.tsx
  src/pages/Products/hooks/useFetchProductData.tsx
  src/pages/Products/hooks/useSearchKeyword.tsx
  src/pages/Products/index.style.ts
  src/pages/Products/index.tsx
  src/store/slices/productsSlice.ts
  src/utils/hooks/useAnimation.tsx
Labels: 💻FE, ⛏Feat

#99 [CB-523] 반려동물 등록 페이지 수정
  src/components/BottomSheet/BreedBottomSheet.tsx
  src/components/Button/index.style.ts
  src/components/Button/index.test.tsx
  src/components/Button/index.tsx
  src/components/Form/FormButton.tsx
  src/components/Form/FormInput.test.tsx
  src/components/Form/FormInput.tsx
  src/pages/Login/components/EmailLoginForm.tsx
  src/pages/RegisterPet/Step1.tsx
  src/pages/RegisterPet/Step2.tsx
  src/pages/RegisterPet/Step3.tsx
  src/pages/RegisterPet/Step4.tsx
  src/pages/RegisterPet/Step5.tsx
  src/pages/RegisterPet/index.style.ts
  tailwind.config.js
Labels: 💻FE, ✒ Design, 📐ReFactor

#102 [CB-540] 페이지 컴포넌트 Lazy loading 및 vendor chunk splitting 적용
  .github/workflows/development_CI_CD.yml
  .github/workflows/main_deploy .yml
  package-lock.json
  package.json
  src/components/Button/index.tsx
  src/pages/Daily/DailyPage.tsx
  src/pages/Daily/hooks/useDailyRecordOverview.tsx
  src/pages/Products/ProductDetail.tsx
  vite.config.ts
Labels: 💻FE, 📐ReFactor

#112 [CB-566] 반려동물 등록과 수정 페이지 동기화
  src/components/ActivitySelector.tsx
  src/components/BottomSheet/BirthdayBottomSheet.tsx
  src/pages/Mypage/pets/[id]/edit.tsx
  src/pages/RegisterPet/Step4.tsx
  src/pages/RegisterPet/Step5.tsx
Labels: 💻FE, 📐ReFactor

#111 [WIP] Cb 565 feat/search
  src/pages/Products/components/ProductDetail/RecommendInfoDetail/RecomendInfoDetail.tsx
  src/pages/Products/components/Search/index.tsx
  src/pages/Products/components/Search/modal.tsx
Labels: 💻FE, ⛏Feat
