Repository PinkDumbbell/CocoBob-FE, pull requests merged in 2022-09, with the labels that each got.

#71 [CB-375] 모듈 관리 변경
  src/components/BottomSheet/BirthdayBottomSheet.tsx
  src/components/BottomSheet/BottomSheet.tsx
  src/components/BottomSheet/BreedBottomSheet.tsx
  src/components/BottomSheet/MonthsAgeBottomSheet.tsx
  src/components/BottomSheet/index.tsx
  src/components/Form/index.tsx
  src/pages/Daily/BodyWeight/index.tsx
  src/pages/Login/EmailLoginSheet.tsx
  src/pages/Login/SignUpSheet.tsx
  src/pages/Login/components/EmailLoginForm.tsx
  src/pages/Login/components/SignUpForm.tsx
  src/pages/Main/index.tsx
  src/pages/Mypage/Main.tsx
  src/pages/Mypage/Profile.tsx
  src/pages/Mypage/pets/[id].tsx
  src/pages/RegisterPet/Step1.tsx
  src/pages/RegisterPet/Step3.tsx
  src/pages/RegisterPet/Step4.tsx
  src/pages/RegisterPet/Step5.tsx
  src/utils/hooks/index.tsx
  src/utils/hooks/useCurrentPosition.tsx
Labels: FE, ReFactor

#69 [CB-261] 반려동물 삭제 기능
  index.html
  src/App.tsx
  src/components/BottomSheet/BirthdayBottomSheet.tsx
  src/components/BottomSheet/BottomSheet.tsx
  src/components/BottomSheet/BreedBottomSheet.tsx
  src/components/BottomSheet/MonthsAgeBottomSheet.tsx
  src/components/BottomSheet/index.tsx
  src/components/Confirm/ConfirmModal.style.ts
  src/components/Confirm/ConfirmModal.tsx
  src/components/Confirm/ConfirmPortal.tsx
  src/components/Confirm/index.tsx
  src/components/Form/index.tsx
  src/components/Toast/ToastConfirm.tsx
  src/pages/Daily/BodyWeight/index.tsx
  src/pages/Login/EmailLoginSheet.tsx
  src/pages/Login/SignUpSheet.tsx
  src/pages/Login/components/EmailLoginForm.tsx
  src/pages/Login/components/SignUpForm.tsx
  src/pages/Main/index.tsx
  src/pages/Mypage/Main.tsx
  src/pages/Mypage/Profile.tsx
  src/pages/Mypage/components/PetSimpleInfo.tsx
  src/pages/Mypage/pets/[id].tsx
  src/pages/RegisterPet/Step1.tsx
  src/pages/RegisterPet/Step3.tsx
  src/pages/RegisterPet/Step4.tsx
  src/pages/RegisterPet/Step5.tsx
  src/store/api/petApi.ts
  src/store/config.ts
  src/store/slices/confirmSlice.ts
  src/store/slices/toastSlice.ts
  src/store/slices/userSlice.ts
  src/utils/hooks/index.tsx
  src/utils/hooks/useConfirm.tsx
  src/utils/hooks/useCurrentPosition.tsx
  src/utils/hooks/useLogout.tsx
  src/utils/hooks/useToastConfirm.tsx
  src/utils/hooks/useWithdrawal.tsx
Labels: FE, Feat, ReFactor

#67 Cb 238 refactor/products V2
  src/pages/Products/components/Filter/FilterModal.tsx
  src/pages/Products/index.tsx
Labels: ReFactor

#73 [CB-367] 토큰 갱신 API 뮤텍스 락 추가
  package-lock.json
  package.json
  src/store/slices/apiSlice.ts
Labels: FE, Feat, ReFactor

#74 [CB-42] 현재 반려동물 프로필 변경 기능 구현
  src/pages/Mypage/Main.tsx
  src/store/api/userApi.ts
Labels: FE, Feat

#75 [CB-380] 네트워크 오류 시 상태메시지 추가
  src/pages/Main/index.tsx
  src/pages/Products/Recoomend.tsx
  src/pages/Products/index.tsx
Labels: FE, Feat

#76 [CB-238] 상품 좋아요 기능 수정
  src/@type/product.ts
  src/pages/Main/components/SwiperProductItem.tsx
  src/store/api/productApi.ts
  src/store/slices/apiSlice.ts
Labels: FE, Feat, ReFactor

#78 Cb 238 feat/products
  src/@type/product.ts
  src/pages/Products/ProductDetail.tsx
  src/pages/Products/components/Search/index.tsx
  src/pages/Products/index.style.ts
  src/store/api/productApi.ts
Labels: FE, Feat
