Repository PinkDumbbell/CocoBob-FE, pull requests merged in 2022-08, with the labels that each got.

#31 [CB-202] AlertMessage 컴포넌트 수정
  package-lock.json
  package.json
  src/App.tsx
  src/components/Toast/ToastMessage.tsx
  src/pages/Login/components/EmailLoginForm.tsx
  src/store/config.ts
  src/store/slices/toastSlice.ts
  src/utils/hooks/useToastMessage.tsx
Labels: FE, Feat

#39 [CB-171] 하단바 스타일 및 페이지 이동 애니메이션 수정
  package-lock.json
  package.json
  src/App.tsx
  src/assets/icon/navbar_daily.svg
  src/assets/icon/navbar_food.svg
  src/assets/icon/navbar_home.svg
  src/assets/icon/navbar_profile.svg
  src/components/Toast/ToastMessage.tsx
  src/components/layout/Footer.style.ts
  src/components/layout/Footer.tsx
  src/components/layout/Header.style.ts
  src/components/layout/Layout.style.ts
  src/components/transition/PageTransition.style.ts
  src/components/transition/PageTransition.tsx
  src/pages/404.tsx
  src/routes/PrivateRoutes.tsx
  src/vite-env.d.ts
  vite.config.ts
Labels: FE, Design, ReFactor

#40 [CB-261] 마이페이지 페이지 구성
  src/assets/icon/edit_icon.svg
  src/assets/icon/female_icon.svg
  src/assets/icon/male_icon.svg
  src/assets/image/pet_default.png
  src/components/transition/PageTransition.tsx
  src/pages/Mypage/Main.tsx
  src/pages/Mypage/Pets.tsx
  src/pages/Mypage/Profile.tsx
  src/pages/Mypage/Wish.tsx
  src/pages/Mypage/components/AddPetButton.tsx
  src/pages/Mypage/components/PetSimpleInfo.tsx
  src/pages/Mypage/index.tsx
  src/routes/PrivateRoutes.tsx
Labels: FE, Feat

#43 [Hotfix] uuid와 Jest 버전 호환 불가로 인한 테스트 에러 해결
  package-lock.json
  package.json
Labels: 😎 Fix

#44 [CB-110] 테스트 케이스 추가
  src/components/Form/FormButton.test.tsx
  src/components/Form/FormInput.test.tsx
  src/pages/RegisterPet/index.test.tsx
Labels: FE

#48 [Hotfix] 리다이렉트 수정
  src/routes/PrivateRoutes.tsx
Labels: 🐛 Bug, 😎 Fix

#41 [CB-267] 메인페이지 구성
  package-lock.json
  package.json
  src/@type/pet.ts
  src/@type/user.ts
  src/assets/icon/heart.svg
  src/assets/icon/menu_icon.svg
  src/assets/icon/search_icon.svg
  src/assets/icon/won.svg
  src/assets/image/main_doctor.png
  src/assets/image/product_dummy.png
  src/components/ContentsContainer/index.tsx
  src/components/layout/Footer.style.ts
  src/components/layout/Header.style.ts
  src/components/layout/Header.tsx
  src/components/layout/Layout.style.ts
  src/components/layout/Layout.tsx
  src/pages/Main/components/SwiperProductItem.tsx
  src/pages/Main/index.style.ts
  src/pages/Main/index.tsx
  src/pages/RegisterPet/index.tsx
  src/store/api/petApi.ts
  src/store/api/userApi.ts
  src/store/slices/userSlice.ts
Labels: FE, Design, Feat

#42 [CB-238] 상품 관련 페이지 <WIP>
  package-lock.json
  src/assets/icon/go_back_btn.png
  src/assets/icon/search_btn.png
  src/components/Product/index.tsx
  src/components/layout/Header.style.ts
  src/components/layout/Header.tsx
  src/components/layout/Layout.tsx
  src/pages/Main/index.tsx
  src/pages/Products/index.tsx
  src/pages/Search/index.style.ts
  src/pages/Search/index.tsx
  src/routes/PrivateRoutes.tsx
Labels: FE, Feat

#47 [CB-40] 반려동물 등록 API 수정
  src/store/api/petApi.ts
Labels: FE, ReFactor

#49 Cb 238 feat/products
  src/@type/product.ts
  src/components/Product/index.tsx
  src/components/layout/Header.style.ts
  src/pages/Products/index.tsx
  src/store/api/productApi.ts
Labels: FE, Feat

#46 [CB-261] 마이페이지
  src/@type/pet.ts
  src/App.tsx
  src/assets/icon/calendar_icon.svg
  src/assets/icon/trash_icon.svg
  src/components/BottomSheet/BirthdayBottomSheet.tsx
  src/components/BottomSheet/BottomSheet.style.ts
  src/components/BottomSheet/BreedBottomSheet.tsx
  src/components/BottomSheet/MonthsAgeBottomSheet.tsx
  src/components/BottomSheet/hooks/useAgeBottomSheet.tsx
  src/components/Form/FormButton.tsx
  src/components/Form/FormInput.tsx
  src/components/layout/Layout.tsx
  src/components/transition/PageTransition.tsx
  src/pages/404.tsx
  src/pages/Mypage/Main.tsx
  src/pages/Mypage/Pets.tsx
  src/pages/Mypage/Profile.tsx
  src/pages/Mypage/Wish.tsx
  src/pages/Mypage/components/AddPetButton.tsx
  src/pages/Mypage/components/PetSimpleInfo.tsx
  src/pages/Mypage/index.style.ts
  src/pages/Mypage/index.tsx
  src/pages/Mypage/pets/[id].tsx
  src/pages/Mypage/pets/index.tsx
  src/pages/RegisterPet/Step3.tsx
  src/pages/RegisterPet/Step4.tsx
  src/routes/PrivateRoutes.tsx
  src/store/api/petApi.ts
  src/store/api/userApi.ts
  src/store/slices/apiSlice.ts
  src/store/slices/bottomSheetSlice.ts
  src/utils/hooks/useLogout.tsx
  src/utils/hooks/useSearchBreed.tsx
  src/utils/hooks/useSelectImage.tsx
Labels: FE, Feat

#51 [CB-171] 테마 스타일 수정
  README.md
  src/App.tsx
  src/components/Form/FormInput.tsx
  src/components/Toast/ToastConfirm.tsx
  src/components/Toast/ToastMessage.tsx
  src/components/layout/Footer.style.ts
  src/components/layout/Header.style.ts
  src/pages/Login/components/SignUpForm.tsx
  src/pages/Mypage/pets/[id].tsx
  src/pages/RegisterPet/Step3.tsx
  src/pages/RegisterPet/Step4.tsx
  src/pages/RegisterPet/index.tsx
  src/store/slices/apiSlice.ts
  src/store/slices/toastSlice.ts
  src/styled.d.ts
  src/styles/theme.ts
  src/utils/hooks/useLogout.tsx
  src/utils/hooks/useSelectImage.tsx
  src/utils/hooks/useToastConfirm.tsx
  src/utils/hooks/useToastMessage.tsx
Labels: FE, Design

#53 [CB-110] 유닛 테스트 추가
  package-lock.json
  package.json
  src/components/Form/FormInput.tsx
  src/mock/handlers.ts
  src/mock/server.ts
  src/pages/Login/SignUpSheet.tsx
  src/pages/Login/components/SignUpForm.test.tsx
  src/pages/Login/components/SignUpForm.tsx
  src/testSetup.ts
Labels: ReFactor, test

#55 [CB-318] 카카오, 구글, 애플 소셜 로그인 연동
  package-lock.json
  src/App.tsx
  src/pages/Login/components/SocialLoginForm.tsx
  src/pages/Redirect/apple.tsx
  src/pages/Redirect/google.tsx
  src/pages/Redirect/hooks/useRedirect.tsx
  src/pages/Redirect/kakao.tsx
  src/store/api/petApi.ts
  src/store/api/productApi.ts
  src/store/api/types.ts
  src/store/api/userApi.ts
Labels: FE, Feat

#56 [CB-307] 데일리 기록 페이지
  .eslintrc.json
  index.html
  package-lock.json
  package.json
  src/@type/location.ts
  src/assets/icon/location_icon.svg
  src/components/Form/FormInput.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/layout/Layout.tsx
  src/components/transition/PageTransition.tsx
  src/pages/Daily/BodyWeight/index.tsx
  src/pages/Daily/Daily.tsx
  src/pages/Daily/Feeds/index.tsx
  src/pages/Daily/Walk/WalkRecordItem.tsx
  src/pages/Daily/Walk/WalkRecordList.tsx
  src/pages/Daily/Walk/WalkRecordMap.tsx
  src/pages/Daily/Walk/index.tsx
  src/pages/Daily/calendar.css
  src/pages/Daily/index.tsx
  src/pages/Main/index.style.ts
  src/pages/Main/index.tsx
  src/pages/Mypage/pets/[id].tsx
  src/pages/RegisterPet/Step5.tsx
  src/routes/PrivateRoutes.tsx
  src/store/config.ts
  src/store/slices/bottomSheetSlice.ts
  src/store/slices/dailySlice.ts
  src/utils/hooks/useCurrentPosition.tsx
  src/utils/hooks/useToastConfirm.tsx
  src/utils/hooks/useToastMessage.tsx
  src/utils/hooks/useWatchPosition.tsx
  src/utils/libs/date.ts
  src/vite-env.d.ts
  tsconfig.json
  vite.config.ts
Labels: FE, Feat

#54 Cb 238 feat/products
  src/components/layout/Header.tsx
  src/components/transition/PageTransition.tsx
  src/pages/Products/ProductDetail.tsx
  src/pages/Products/components/Nutrient.tsx
  src/pages/Products/components/Search/header.tsx
  src/pages/Products/components/Search/index.style.ts
  src/pages/Products/components/Search/index.tsx
  src/pages/Products/index.tsx
  src/pages/Search/index.tsx
  src/routes/PrivateRoutes.tsx
Labels: FE, Feat

#57 [CB-40] 반려동물 관련 컴포넌트 수정
  .github/workflows/main_deploy .yml
  src/@type/pet.ts
  src/components/BottomSheet/BreedBottomSheet.tsx
  src/pages/Mypage/components/PetSimpleInfo.tsx
  src/pages/Mypage/index.style.ts
  src/pages/Mypage/pets/[id].tsx
  src/pages/RegisterPet/Step1.tsx
  src/pages/RegisterPet/Step2.tsx
  src/pages/RegisterPet/Step3.tsx
  src/pages/RegisterPet/Step4.tsx
  src/pages/RegisterPet/Step5.tsx
  src/pages/RegisterPet/index.test.tsx
  src/pages/RegisterPet/index.tsx
  src/pages/RegisterPet/type.ts
  src/store/api/petApi.ts
  src/store/config.ts
  src/store/slices/registerPetSlice.ts
  src/utils/hooks/useBottomSheet.tsx
  src/utils/hooks/useSearchBreed.tsx
Labels: FE, ReFactor

#58 [CB-7] Flutter 애플리케이션 관련 기능 추가
  package-lock.json
  src/App.tsx
  src/pages/Daily/Daily.tsx
  src/pages/Login/components/SocialLoginForm.tsx
  src/utils/hooks/usePlatform.tsx
Labels: FE, Feat

#61 Cb 238 feat/products
  package-lock.json
  package.json
  src/@type/product.ts
  src/pages/Products/index.tsx
  src/store/api/productApi.ts
Labels: FE, Feat

#64 Cb 238 refactor/products
  index.html
  src/pages/Products/components/Filter/FilterModal.tsx
  src/pages/Products/components/Search/header.tsx
  src/pages/Products/components/Search/index.tsx
  src/pages/Products/components/Search/modal.tsx
  src/pages/Products/index.tsx
  src/portal.tsx
Labels: ReFactor

#65 [CB-307] 데일리 기록 기능
  README.md
  src/assets/icon/calendar_plus.svg
  src/assets/icon/calendar_plus_primary.svg
  src/assets/icon/dog_food.svg
  src/assets/icon/dog_icon.svg
  src/assets/icon/pencil_icon.svg
  src/assets/icon/weight_icon.svg
  src/pages/Daily/Daily.tsx
  src/pages/Daily/components/DailyAddBodyWeight.tsx
  src/pages/Daily/components/DailyAddFeed.tsx
  src/pages/Daily/components/DailyAddNoteModal.tsx
  src/pages/Daily/components/DailyAddWalk.tsx
  src/pages/Daily/components/DailyCalendar.tsx
  src/pages/Daily/components/DailyModal.tsx
  src/store/api/dailyApi.ts
Labels: FE, Feat

#68 [CB-7] 플러터 앱 웹뷰 세팅
  src/pages/Login/EmailLoginSheet.tsx
Labels: FE, Feat
