Repository PinkDumbbell/CocoBob-FE, pull requests merged in 2022-07, with the labels that each got.

#9 CB-90 feat: add HoC for private route pages
  src/App.tsx
  src/routes/PrivateRoute.tsx
  src/routes/PrivateRoutes.tsx
Labels: FE, Feat, ReFactor

#10 CB-98 로그인페이지
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/components/layout/Footer.style.ts
  src/components/layout/Footer.tsx
  src/components/layout/Header.style.ts
  src/components/layout/Header.tsx
  src/components/layout/Layout.style.ts
  src/components/layout/Layout.tsx
  src/components/transition/PageTransition.style.ts
  src/components/transition/PageTransition.tsx
  src/components/transition/hooks/usePrevious.tsx
  src/index.css
  src/pages/Login/components/EmailLoginForm.style.ts
  src/pages/Login/components/EmailLoginForm.tsx
  src/pages/Login/components/LoginSubmenus.style.ts
  src/pages/Login/components/LoginSubmenus.tsx
  src/pages/Login/components/SocialLoginForm.style.ts
  src/pages/Login/components/SocialLoginForm.tsx
  src/pages/Login/email.tsx
  src/pages/Login/index.style.ts
  src/pages/Login/index.tsx
Labels: FE, Feat

#11 CB-109 Storybook 디자인 시스템 적용
  .github/.gitmessage.txt
  .storybook/main.js
  .storybook/preview-head.html
  .storybook/preview.js
  package-lock.json
  package.json
  src/stories/Button.stories.tsx
  src/stories/Button.tsx
  src/stories/Header.stories.tsx
  src/stories/Header.tsx
  src/stories/Introduction.stories.mdx
  src/stories/Page.stories.tsx
  src/stories/Page.tsx
  src/stories/assets/code-brackets.svg
  src/stories/assets/colors.svg
  src/stories/assets/comments.svg
  src/stories/assets/direction.svg
  src/stories/assets/flow.svg
  src/stories/assets/plugin.svg
  src/stories/assets/repo.svg
  src/stories/assets/stackalt.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
Labels: FE, Design, Feat

#12 CB-23 자체 로그인
  .eslintrc.json
  package-lock.json
  package.json
  src/@type/pet.ts
  src/@type/user.ts
  src/components/FormInput.tsx
  src/components/layout/Footer.style.ts
  src/components/layout/Footer.tsx
  src/components/layout/Header.style.ts
  src/components/layout/Header.tsx
  src/components/layout/Layout.style.ts
  src/components/layout/Layout.tsx
  src/main.tsx
  src/pages/Login/components/EmailLoginForm.style.ts
  src/pages/Login/components/EmailLoginForm.tsx
  src/pages/Login/components/Form.tsx
  src/pages/Login/components/LoginSubmenus.style.ts
  src/pages/Login/components/LoginSubmenus.tsx
  src/pages/Login/components/SocialLoginForm.style.ts
  src/pages/Login/components/SocialLoginForm.tsx
  src/pages/Login/email.tsx
  src/pages/Login/index.style.ts
  src/pages/Login/index.tsx
  src/pages/Login/types.ts
  src/pages/Main/index.tsx
  src/services/userService.ts
  src/store/config.ts
  src/store/slices/authSlice.ts
  src/store/slices/userSlice.ts
  src/utils/api/types.ts
  src/utils/api/userApi.ts
  src/utils/hooks/useUser.tsx
Labels: FE, Feat

#13 CB-100 [FE] 회원가입 페이지 UI
  package-lock.json
  src/App.tsx
  src/components/transition/PageTransition.tsx
  src/pages/Login/components/EmailLoginForm.tsx
  src/pages/Login/components/LoginSubmenus.style.ts
  src/pages/Login/components/LoginSubmenus.tsx
  src/pages/SignUp/components/SignUpForm.style.ts
  src/pages/SignUp/components/SignUpForm.tsx
  src/pages/SignUp/index.style.ts
  src/pages/SignUp/index.tsx
Labels: FE, Feat

#14 CB-83 모바일 UI 글로벌 스타일 적용
  .storybook/main.js
  .storybook/preview.js
  package-lock.json
  package.json
  postcss.config.js
  src/App.css
  src/App.tsx
  src/components/Button/index.stories.tsx
  src/components/Button/index.tsx
  src/components/stories/Introduction.stories.mdx
  src/favicon.svg
  src/index.css
  src/logo.svg
  src/main.tsx
  src/stories/Button.stories.tsx
  src/stories/Button.tsx
  src/stories/Header.stories.tsx
  src/stories/Header.tsx
  src/stories/Introduction.stories.mdx
  src/stories/Page.stories.tsx
  src/stories/Page.tsx
  src/stories/assets/code-brackets.svg
  src/stories/assets/colors.svg
  src/stories/assets/comments.svg
  src/stories/assets/direction.svg
  src/stories/assets/flow.svg
  src/stories/assets/plugin.svg
  src/stories/assets/repo.svg
  src/stories/assets/stackalt.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  src/styles/Globalstyles.ts
  tailwind.config.js
Labels: FE, Design, Feat

#16 CB-100 [FE] 회원가입 페이지 UI <추가>
  package-lock.json
  src/components/Form/FormButton.tsx
  src/components/Form/FormInput.tsx
  src/pages/Login/components/EmailLoginForm.tsx
  src/pages/SignUp/components/SignUpForm.style.ts
  src/pages/SignUp/components/SignUpForm.tsx
  src/pages/SignUp/index.style.ts
  src/pages/SignUp/index.tsx
Labels: FE, Feat

#25 [CB-166] hotfix: jest test 에러 해결
  babel.config.js
  babel.config.json
  jest.config.json
  package-lock.json
  package.json
  src/store/config.ts
  src/store/slices/apiSlice.ts
  src/utils/api/index.ts
  src/vite-env.d.ts
  tsconfig.json
Labels: FE, 😎 Fix

#28 [CB-99] 로그인 토큰 & persist store
  package-lock.json
  package.json
  src/components/BottomSheet/index.tsx
  src/main.tsx
  src/pages/Login/api.ts
  src/pages/Login/components/SignUpForm.style.ts
  src/pages/Login/components/SignUpForm.tsx
  src/pages/Login/index.style.ts
  src/store/api/userApi.ts
  src/store/config.ts
Labels: FE, Design, ReFactor

#29 [CB-166] 빌드 에러 수정
  src/store/api/userApi.ts
Labels: 🐛 Bug, 😎 Fix

#30 빌드 에러 수정
  src/store/api/userApi.ts
Labels: 🐛 Bug, 😎 Fix

#32 [CB-99] 유저 상태 관리 수정
  src/@type/user.ts
  src/pages/Login/index.tsx
  src/pages/Main/index.tsx
  src/routes/PrivateRoutes.tsx
  src/store/api/types.ts
  src/store/api/userApi.ts
  src/store/config.ts
  src/store/slices/apiSlice.ts
  src/store/slices/authSlice.ts
  src/utils/hooks/useLogout.tsx
Labels: FE, Feat, ReFactor

#33 [CB-40] 반려동물 등록 페이지
  package-lock.json
  package.json
  src/@type/pet.ts
  src/@type/user.ts
  src/assets/icon/btn_add_photo.png
  src/components/Form/FormButton.tsx
  src/components/Form/FormInput.tsx
  src/components/layout/Header.tsx
  src/components/layout/Layout.tsx
  src/components/transition/PageTransition.tsx
  src/pages/Login/SignUpSheet.tsx
  src/pages/Login/components/EmailLoginForm.tsx
  src/pages/Login/components/JoinLink.tsx
  src/pages/Login/components/SignUpForm.tsx
  src/pages/Login/index.tsx
  src/pages/Main/index.tsx
  src/pages/RegisterPet/Step1.tsx
  src/pages/RegisterPet/Step2.tsx
  src/pages/RegisterPet/Step3.tsx
  src/pages/RegisterPet/Step4.tsx
  src/pages/RegisterPet/Step5.tsx
  src/pages/RegisterPet/hooks/useSearchBreed.tsx
  src/pages/RegisterPet/index.style.ts
  src/pages/RegisterPet/index.tsx
  src/pages/RegisterPet/type.ts
  src/routes/PrivateRoutes.tsx
  src/store/api/petApi.ts
  src/store/config.ts
  src/store/slices/apiSlice.ts
  src/store/slices/authSlice.ts
  src/store/slices/bottomSheetSlice.ts
  src/store/slices/registerPetSlice.ts
  src/store/slices/userSlice.ts
  src/store/testUtils.ts
  src/styles/Globalstyles.ts
  src/utils/api/index.ts
  src/utils/constants/enrollment.ts
  src/utils/hooks/useBottomSheet.tsx
  src/utils/hooks/useSelectImage.tsx
  src/utils/hooks/useUser.tsx
  src/utils/libs/date.ts
  src/utils/libs/getFileFromObjectURL.ts
  tailwind.config.js
Labels: FE, Feat

#35 [CB-254] API 응답 형식 변경에 따른 수정
  src/store/api/types.ts
  src/store/api/userApi.ts
  src/store/slices/apiSlice.ts
  src/store/slices/authSlice.ts
Labels: FE, ReFactor

#34 [CB-131] 공통 스타일 업데이트
  package-lock.json
  package.json
  src/assets/icon/checkbox.png
  src/components/BottomSheet/index.tsx
  src/components/Button/index.tsx
  src/components/ChipButton/index.style.tsx
  src/components/ChipButton/index.tsx
  src/components/Form/FormButton.tsx
  src/components/layout/Footer.style.ts
  src/components/layout/Layout.style.ts
  src/components/layout/Layout.tsx
  src/components/transition/PageTransition.style.ts
  src/components/transition/PageTransition.tsx
  src/main.tsx
  src/pages/Login/EmailLoginSheet.tsx
  src/pages/Login/components/JoinLink.tsx
  src/pages/Login/components/SignUpForm.style.ts
  src/pages/Login/index.style.ts
  src/pages/Main/index.tsx
  src/pages/RegisterPet/Step3.tsx
  src/pages/RegisterPet/Step4.tsx
  src/pages/RegisterPet/Step5.tsx
  src/pages/RegisterPet/index.style.ts
  src/styles/Globalstyles.ts
  src/styles/index.css
  src/styles/theme.ts
  tailwind.config.js
Labels: FE, Design

#36 [CB-40] 견종 불러오기 API 적용
  src/@type/pet.ts
  src/pages/RegisterPet/Step3.tsx
  src/pages/RegisterPet/Step5.tsx
  src/pages/RegisterPet/hooks/useSearchBreed.tsx
  src/pages/RegisterPet/index.tsx
  src/store/api/petApi.ts
  src/store/slices/apiSlice.ts
  src/store/slices/authSlice.ts
  src/utils/constants/enrollment.ts
Labels: FE, Feat
