Repository PinkDumbbell/CocoBob-FE, pull requests merged in 2022-10, with the labels that each got.

#81 [CB-417] 개인정보 처리방침 페이지 추가
  src/components/BottomSheet/BottomSheet.tsx
  src/pages/Login/EmailLoginSheet.tsx
  src/pages/Login/SignUpPrivacyPolicy.tsx
  src/pages/Login/SignUpSheet.tsx
  src/pages/Login/index.tsx
Labels: 💻FE, ⛏Feat, 😎 Fix

#83 [CB-470] 새로운 스타일 적용
  index.html
  src/assets/icon/add_icon_small.png
  src/assets/icon/btn_google_signin.png
  src/assets/icon/dog_icon.png
  src/assets/icon/google_logo.png
  src/assets/icon/header_back.webp
  src/assets/icon/kakao_logo.png
  src/assets/icon/search_btn.webp
  src/assets/icon/settings_icon.png
  src/assets/image/main_doctor.webp
  src/assets/image/pet_default.webp
  src/assets/image/petalog_main.webp
  src/components/ContentsContainer/index.tsx
  src/components/layout/Layout.tsx
  src/pages/Login/components/AppleLoginButton.tsx
  src/pages/Login/components/SocialLoginForm.style.ts
  src/pages/Login/components/SocialLoginForm.tsx
  src/pages/Login/index.style.ts
  src/pages/Login/index.tsx
  src/pages/Main/components/MainContentButton.tsx
  src/pages/Main/components/SwiperProductItem.tsx
  src/pages/Main/index.style.ts
  src/pages/Main/index.tsx
  src/pages/Mypage/Main.tsx
  src/pages/Mypage/Profile.tsx
  src/pages/Mypage/components/AddPetButton.tsx
  src/pages/Mypage/components/PetSimpleInfo.tsx
  src/pages/Mypage/index.style.ts
  src/pages/Mypage/pets/[id].tsx
  src/pages/Mypage/pets/[id]/edit.tsx
  src/pages/Mypage/pets/[id]/index.tsx
  src/pages/Mypage/pets/index.tsx
  src/pages/Products/index.tsx
  src/routes/PrivateRoutes.tsx
  src/store/slices/authSlice.ts
Labels: 💻FE, ✒ Design, 📐ReFactor

#84 Cb 238 상품 상세 페이지 에러 수정
  .husky/pre-commit
  src/pages/Products/components/Search/index.tsx
Labels: 💻FE, 😎 Fix

#85 Cb 238 상품 상세페이지 검색 에러 수정
  src/store/api/productApi.ts
Labels: 💻FE, 😎 Fix

#86 배포 환경 버그 수정
  package-lock.json
  package.json
  src/App.tsx
  src/components/BottomSheet/BottomSheet.style.ts
  src/components/BottomSheet/BreedBottomSheet.tsx
  src/components/ChipButton/index.style.tsx
  src/components/DatePicker/DatePicker.css
  src/components/DatePicker/DatePicker.tsx
  src/components/DatePicker/index.ts
  src/components/Form/FormInput.tsx
  src/pages/Daily/Walk/WalkRecordPage.tsx
  src/pages/Daily/Walk/components/WalkRecordToolbar.tsx
  src/pages/Daily/Walk/hooks/useLocationInApp.tsx
  src/pages/Daily/Walk/index.tsx
  src/pages/Login/index.style.ts
  src/pages/Main/index.tsx
  src/pages/Mypage/Main.tsx
  src/pages/Mypage/components/AddPetButton.tsx
  src/pages/Mypage/index.style.ts
  src/pages/Products/index.tsx
  src/pages/RegisterPet/Step3.tsx
  src/pages/RegisterPet/Step4.tsx
  src/pages/RegisterPet/Step5.tsx
  src/pages/RegisterPet/index.tsx
  src/store/slices/platformSlice.ts
  src/styles/Globalstyles.ts
  src/utils/hooks/index.tsx
  src/utils/hooks/usePlatform.tsx
Labels: 💻FE, ⛏Feat, 😎 Fix

#88 hotfix: kakao map undefined error
  src/pages/Daily/Walk/WalkRecordPage.tsx
  src/pages/Daily/Walk/components/WalkRecordMap.tsx
  src/store/slices/platformSlice.ts
  src/utils/hooks/useKakaoMap.tsx
Labels: 🐛 Bug, 😎 Fix

#89 플랫폼 및 위치권한 핸들러 수정
  src/App.tsx
  src/pages/Daily/Walk/hooks/useLocationInApp.tsx
  src/pages/Daily/Walk/index.tsx
  src/pages/Login/components/SocialLoginForm.tsx
  src/store/slices/platformSlice.ts
Labels: 🐛 Bug, 😎 Fix

#90 hotfix: layout height calculate error
  src/App.tsx
  src/components/Form/FormInput.tsx
  src/pages/RegisterPet/Step3.tsx
  src/utils/hooks/useVh.tsx
Labels: 🐛 Bug, 💻FE, 😎 Fix

#91 hotfix: modify location permission handler for iOS
  src/pages/Daily/Walk/hooks/useLocationInApp.tsx
Labels: 🐛 Bug, 💻FE, 😎 Fix

#87 [CB-489] 상품 필터 검색
  index.html
  package-lock.json
  src/@type/product.ts
  src/assets/icon/filter_icon.svg
  src/assets/icon/refresh_icon.svg
  src/pages/Mypage/Main.tsx
  src/pages/Mypage/components/AddPetButton.tsx
  src/pages/Mypage/components/HeaderAddPetButton.tsx
  src/pages/Mypage/index.style.ts
  src/pages/Mypage/pets/index.tsx
  src/pages/Products/ProductDetail.tsx
  src/pages/Products/components/Filter/FilterAllContent.tsx
  src/pages/Products/components/Filter/FilterModal.tsx
  src/pages/Products/components/Filter/constant.ts
  src/pages/Products/components/ProductList/ProductList.tsx
  src/pages/Products/components/ProductList/ProductListItem.tsx
  src/pages/Products/hooks/useFetchProductData.tsx
  src/pages/Products/hooks/useFilterSheet.tsx
  src/pages/Products/hooks/useSearchKeyword.tsx
  src/pages/Products/index.tsx
  src/store/api/productApi.ts
  src/store/config.ts
  src/store/slices/productsSlice.ts
  src/styles/index.css
Labels: 💻FE, ⛏Feat, 📐ReFactor
