Repository PinkDumbbell/CocoBob-FE, pull requests merged in 2022-12, with the labels that each got.

#113 [CB-569] 개발 브랜치 GCP 배포
  .github/workflows/gcp_cloud_run.yml
  Dockerfile
  nginx.conf
  package-lock.json
  package.json
  vite.config.ts
Labels: 💻FE, ⛏Feat

#114 Release Main
  .github/workflows/gcp_cloud_run_develop.yml
  .github/workflows/gcp_cloud_run_main.yml
  Dockerfile
  Dockerfile.dev
  Dockerfile.prod
  cloudbuild.dev.yml
  cloudbuild.prod.yml
  nginx.conf
  package-lock.json
  package.json
  src/pages/Products/components/ProductDetail/RecommendInfoDetail/RecomendInfoDetail.tsx
  src/pages/Products/components/Search/index.tsx
  src/pages/Products/components/Search/modal.tsx
  src/store/slices/apiSlice.ts
  vite.config.ts
Labels: 💻FE, ⛏Feat, 📐ReFactor

#110 [CB-247] 온보딩 애니메이션
  src/Animation/OnBoarding/assets/display.json
  src/Animation/OnBoarding/assets/display2.json
  src/Animation/OnBoarding/assets/display3.json
  src/Animation/Spinner/index.style.ts
  src/pages/Login/index.tsx
  src/pages/OnBoarding/index.constant.ts
  src/pages/OnBoarding/index.style.ts
  src/pages/OnBoarding/index.tsx
Labels: 💻FE, ✒ Design, ⛏Feat
